# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Techtopia
tagline:             'Kingdom of Tech '
description:         '.'
url:                 http://heejoonshin.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Shin heejoon
  url:               heejoonshin@github.io
  email:             shinhj88@gmail.com

# Custom vars
version:             1.0.0


category_dir: category/
tag_dir: tag/
excerpt_separator: ""
